name: skip-workflow
author: saulmaldonado
description: 'skip workflow based on commit message(s) pull requests'
inputs:
  phrase:
    description: 'string to search for in commit message(s)'
    required: false
    default: 'docs'
  github-token:
    description: Github Token
    required: true
runs:
  using: 'node12'
  main: 'dist/main.js'
  # post: 'dist/post.js'
