on: [pull_request]

jobs:
  check-commit:
    runs-on: ubuntu-latest
    name: check commit
    outputs:
      skip-job: ${{ steps.skip-workflow.outputs.skip-job }}
    steps:
      - uses: actions/checkout@v2
      - name: skip-workflow
        id: skip-workflow
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  test-action:
    needs: check-commit
    if: ${{ !needs.check-commit.outputs.skip-job }}
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: test command
        run: yarn test
      - name: test command 2
        run: yarn test
  test-action2:
    needs: check-commit
    if: ${{ !needs.check-commit.outputs.skip-job }}
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: test command
        run: yarn test
      - name: test command 2
        run: yarn test
