on: [pull_request]

jobs:
  test-action:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v2
      - name: skip-workflow
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: test command
        if: ${{ steps['skip-workflow'].outputs.match }}
        run: yarn test
      - name: test command 2
        if: ${{ steps.skip-workflow.outputs.match }}
        run: yarn test
