on: [pull_request]

jobs:
  test-action:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: skip-workflow
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: test command
        run: yarn test
