# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Issue Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: saulmaldonado/skip-workflow@v1.1.0
      with:
        phrase: '[skip-workflow]'
        search: '["commit_messages", "pull_request"]'
        github-token: ${{ secrets.GITHUB_TOKEN }}
